# Generated by Django 2.1.1 on 2019-02-17 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'price_feature',
            },
        ),
        migrations.CreateModel(
            name='PricePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_type', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Monthly', max_length=40)),
                ('value', models.IntegerField(default=0)),
                ('start_at', models.DateTimeField(null=True)),
                ('end_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'price_payment',
            },
        ),
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('short_description', models.TextField(null=True)),
                ('long_description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'price_plan',
            },
        ),
        migrations.CreateModel(
            name='PricePlanFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.PriceFeature')),
                ('price_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.PricePlan')),
            ],
            options={
                'db_table': 'price_plan_feature',
            },
        ),
        migrations.CreateModel(
            name='SpUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=255, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True, unique=True)),
                ('phone', models.CharField(max_length=255, null=True, unique=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('company_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('avatar', models.CharField(blank=True, max_length=1024, null=True)),
                ('activated', models.BooleanField(default=False)),
                ('whitelisting', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sp_user',
            },
        ),
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('order_number', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'template_category',
            },
        ),
        migrations.CreateModel(
            name='TemplateCategoryContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.TemplateCategory')),
            ],
            options={
                'db_table': 'template_category_content',
            },
        ),
        migrations.CreateModel(
            name='TemplateContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.TextField(null=True)),
                ('template_categories', models.ManyToManyField(through='chatbot.TemplateCategoryContent', to='chatbot.TemplateCategory')),
            ],
            options={
                'db_table': 'template_content',
            },
        ),
        migrations.CreateModel(
            name='UserPricePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField(null=True)),
                ('end_at', models.DateTimeField(null=True)),
                ('price_payment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chatbot.PricePayment')),
                ('sp_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chatbot.SpUser')),
            ],
            options={
                'db_table': 'user_price_payment',
            },
        ),
        migrations.AddField(
            model_name='templatecategorycontent',
            name='template_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.TemplateContent'),
        ),
        migrations.AddField(
            model_name='pricepayment',
            name='price_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.PricePlan'),
        ),
        migrations.AddField(
            model_name='pricefeature',
            name='price_plans',
            field=models.ManyToManyField(through='chatbot.PricePlanFeature', to='chatbot.PricePlan'),
        ),
        migrations.AlterUniqueTogether(
            name='templatecategorycontent',
            unique_together={('template_category', 'template_content')},
        ),
    ]
