# Generated by Django 2.1.1 on 2019-02-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatecontent',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
