# Generated by Django 2.1.1 on 2019-02-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20190218_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spuser',
            name='avatar',
            field=models.ImageField(default='', upload_to='static/img/spuser'),
        ),
        migrations.AlterField(
            model_name='templatecontent',
            name='image',
            field=models.ImageField(default='static/img/minibot-logo.png', upload_to='static/img/templatecontent/'),
        ),
    ]
