# Generated by Django 2.1.1 on 2019-02-26 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_auto_20190218_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecategory',
            name='data_type',
            field=models.CharField(default='', max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterField(
            model_name='pricefeature',
            name='name',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterField(
            model_name='pricepayment',
            name='value',
            field=models.IntegerField(default=0, validators=[django.core.validators.validate_integer]),
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterField(
            model_name='spuser',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterField(
            model_name='spuser',
            name='company_url',
            field=models.CharField(blank=True, max_length=1024, null=True, validators=[django.core.validators.MaxLengthValidator(1024)]),
        ),
        migrations.AlterField(
            model_name='spuser',
            name='email',
            field=models.CharField(max_length=255, null=True, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='spuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterField(
            model_name='spuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterField(
            model_name='spuser',
            name='phone',
            field=models.CharField(max_length=255, null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterField(
            model_name='spuser',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterField(
            model_name='templatecategory',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterField(
            model_name='templatecategory',
            name='order_number',
            field=models.IntegerField(default=0, validators=[django.core.validators.validate_integer]),
        ),
        migrations.AlterField(
            model_name='templatecontent',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
    ]
