# Generated by Django 2.1.1 on 2019-03-13 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_auto_20190311_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spuser',
            name='avatar',
            field=models.ImageField(blank=True, default='', null=True, upload_to='static/img/spuser'),
        ),
        migrations.AlterField(
            model_name='spuser',
            name='email',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
