# Generated by Django 2.1.1 on 2019-03-18 00:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_auto_20190314_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecategory',
            name='url_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
    ]
