# Generated by Django 2.1.1 on 2019-03-19 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_templatecategory_url_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceFeature_PricePlan',
        ),
        migrations.AlterModelOptions(
            name='pricefeature',
            options={},
        ),
        migrations.AlterModelOptions(
            name='priceplanfeature',
            options={},
        ),
        migrations.AddField(
            model_name='priceplan',
            name='monthly_cost',
            field=models.IntegerField(default=0, validators=[django.core.validators.validate_integer]),
        ),
        migrations.AddField(
            model_name='priceplan',
            name='yearly_cost',
            field=models.IntegerField(default=0, validators=[django.core.validators.validate_integer]),
        ),
    ]
